{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggplate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggplate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggplate/ggplate_{{ version }}.tar.gz
  sha256: a10aa17aa5002c1890838a811ecf68b195c5ab49fca806c736b6cb2c356e3b45

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-farver
    - r-forcats
    - r-ggplot2
    - r-purrr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-farver
    - r-forcats
    - r-ggplot2
    - r-purrr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tidyr

test:
  commands:
    - $R -e "library('ggplate')"           # [not win]
    - "\"%R%\" -e \"library('ggplate')\""  # [win]

about:
  home: https://github.com/jpquast/ggplate, https://jpquast.github.io/ggplate/
  license: MIT
  summary: Enables users to create simple plots of biological culture plates as well as microplates.
    Both continuous and discrete values can be plotted onto the plate layout.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - jpquast

# Package: ggplate
# Title: Create Layout Plots of Biological Culture Plates and Microplates
# Version: 0.1.0
# Authors@R: person(given = "Jan-Philipp", family = "Quast", role = c("aut", "cre"), email = "quast@imsb.biol.ethz.ch", comment = c(ORCID = "0000-0003-2713-778X"))
# Description: Enables users to create simple plots of biological culture plates as well as microplates. Both continuous and discrete values can be plotted onto the plate layout.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# Imports: dplyr, ggplot2, scales, purrr, rlang, stringr, tidyr, utils, forcats, farver
# Suggests: covr, testthat (>= 3.0.0)
# Depends: R (>= 4.0)
# URL: https://github.com/jpquast/ggplate, https://jpquast.github.io/ggplate/
# BugReports: https://github.com/jpquast/ggplate/issues
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2023-11-10 16:36:44 UTC; jan-philippquast
# Author: Jan-Philipp Quast [aut, cre] (<https://orcid.org/0000-0003-2713-778X>)
# Maintainer: Jan-Philipp Quast <quast@imsb.biol.ethz.ch>
# Repository: CRAN
# Date/Publication: 2023-11-10 18:53:23 UTC
